// src/types/types.ts
/// <reference types="wicg-file-system-access" />
export interface MindNode {
  id: string;
  content: string;         // Huvudinnehåll (Texten för textkort, HTML för Zotero, Bild-tagg för bilder)
  x: number;
  y: number;
  z: number;
  tags: string[];
  createdAt: string;
  
  // NYA FÄLT
  type: 'text' | 'image' | 'zotero'; // För att veta hur vi ska rendera
  caption?: string;        // Synlig text under kortet (visas alltid)
  comment?: string;        // Dold kommentar (visas vid hover, stödjer markdown/länkar)
  ocrText?: string;        // "Baksidan" av kortet (AI-texten)
  isFlipped?: boolean;     // Om vi tittar på baksidan just nu (sparas ej till fil nödvändigtvis)
  selected?: boolean;      // För bulk-hantering
  
  // Pin/Lock
  pinned?: boolean;        // Om kortet är låst på plats (kan inte flyttas)

  // Storlek (för viewport culling)
  width?: number;
  height?: number;
  backgroundColor?: string; // Optional custom background color for the node
  accentColor?: string;     // Accent color stripe (e.g. from Zotero highlight)

  // PHASE 2: AI/Embeddings
  embedding?: number[];    // OpenAI embedding vector (1536 dimensions for text-embedding-3-small)
  semanticTags?: string[]; // AI-genererade konceptuella taggar
  lastEmbedded?: string;   // Timestamp för när embedding skapades

  // Selection Scope (transient, ej sparad till fil)
  scopeDegree?: number;    // 0 = ej scope, 1-5 = grad av koppling från bas-selektion
}

export interface Synapse {
  id: string;
  sourceId: string;
  targetId: string;
  strength: number;
  autoGenerated?: boolean; // Om länken skapades av AI (semantisk likhet)
  similarity?: number;     // Semantisk likhetsscore (0-1)
}

// Ordnad sekvens av kort (D+klick för att kedja)
export interface Sequence {
  id: string;
  nodeIds: string[];       // Ordnad lista av nod-IDs
  createdAt: string;
}

export type AIProvider = 'gemini' | 'openai' | 'claude';

export interface BrainState {
  nodes: Map<string, MindNode>; // Changed to Map
  synapses: Synapse[];
  fileHandle: FileSystemDirectoryHandle | null; // Changed to DirectoryHandle for folder-based system
  lastSaved: string | null;
  
  // API Keys
  geminiKey?: string;
  openaiKey?: string;
  claudeKey?: string;
  
  // AI Settings
  autoLinkThreshold?: number;  // Tröskelvärde för auto-linking (0-1, default 0.75)
  enableAutoLink?: boolean;    // Om auto-linking är aktiverat
}

// AI Reflection/Question från Claude
export interface AIReflection {
  question: string;
  context: string[];  // Node IDs som triggade frågan
  timestamp: string;
}
