// src/types/types.ts
/// <reference types="wicg-file-system-access" />
// View mode för canvas vs kolumn-vy
export type ViewMode = 'canvas' | 'column';

// Sorteringsalternativ för kolumn-vy
export type SortOption = 'connections' | 'tags' | 'oldest' | 'newest' | 'modified' | 'copied' | 'value-high' | 'value-low';

export interface MindNode {
  id: string;
  content: string;         // Huvudinnehåll (Texten för textkort, OCR-text för bilder, HTML för Zotero)
  x: number;
  y: number;
  z: number;
  tags: string[];
  title?: string;          // Kortets rubrik (AI-genererad eller manuell)
  createdAt: string;
  updatedAt?: string;      // Last updated (sorting)
  copyRef?: string;        // Original card id if this is a copy
  copiedAt?: string;       // When this copy was created
  originalCreatedAt?: string; // When the original card was created
  imageRef?: string;       // Bildens filreferens/URL (för bildkort)

  // NYA FÄLT
  type: 'text' | 'image' | 'zotero'; // För att veta hur vi ska rendera
  caption?: string;        // Synlig text under kortet (visas alltid)
  comment?: string;        // Dold kommentar (visas vid hover, stödjer markdown)
  link?: string;           // Dedikerad länk (markdown format: [name](url))
  ocrText?: string;        // "Baksidan" av kortet (AI-texten)
  isFlipped?: boolean;     // Om vi tittar på baksidan just nu (sparas ej till fil nödvändigtvis)
  selected?: boolean;      // Legacy: selection hanteras i store (selectedNodeIds)

  // Pin/Lock
  pinned?: boolean;        // Om kortet är låst på plats (kan inte flyttas)

  // Storlek (för viewport culling)
  width?: number;
  height?: number;
  backgroundColor?: string; // Optional custom background color for the node
  accentColor?: string;     // Accent color stripe (e.g. from Zotero highlight)

  // PHASE 2: AI/Embeddings
  embedding?: number[];    // OpenAI embedding vector (1536 dimensions for text-embedding-3-small)
  semanticTags?: string[]; // AI-genererade konceptuella taggar
  lastEmbedded?: string;   // Timestamp för när embedding skapades

  // Rating/Value
  value?: number;          // 1-6 (1=Highest, 6=Lowest)
  event?: string;          // Event date/time string (e.g. YYMMDD_HHMM or ISO)
  remindAt?: string;       // Reminder date/time string(s), comma separated

  // Selection Scope (transient, ej sparad till fil)
  scopeDegree?: number;    // 0 = ej scope, 1-6 = grad av koppling från bas-selektion
}

export interface Synapse {
  id: string;
  sourceId: string;
  targetId: string;
  strength: number;
  autoGenerated?: boolean; // Om länken skapades av AI (semantisk likhet)
  similarity?: number;     // Semantisk likhetsscore (0-1)
}

// Ordnad sekvens av kort (D+klick för att kedja)
export interface Sequence {
  id: string;
  nodeIds: string[];       // Ordnad lista av nod-IDs
  createdAt: string;
}

// Session - arbetsyta/projekt med urval av kort
export interface Session {
  id: string;
  name: string;
  cardIds: string[];          // Kort i sessionen (sparas som array för JSON)
  viewState: {
    x: number;
    y: number;
    zoom: number;
  };
  createdAt: number;
  lastOpened: number;
}

export type AIProvider = 'gemini' | 'openai' | 'claude';

export interface BrainState {
  nodes: Map<string, MindNode>; // Changed to Map
  synapses: Synapse[];
  fileHandle: FileSystemDirectoryHandle | null; // Changed to DirectoryHandle for folder-based system
  lastSaved: string | null;

  // API Keys
  geminiKey?: string;
  openaiKey?: string;
  claudeKey?: string;

  // AI Settings
  autoLinkThreshold?: number;  // Tröskelvärde för auto-linking (0-1, default 0.75)
  enableAutoLink?: boolean;    // Om auto-linking är aktiverat
}

// AI Reflection/Question från Claude
export interface AIReflection {
  question: string;
  context: string[];  // Node IDs som triggade frågan
  timestamp: string;
}
// Samtalsminne - ett meddelande i en konversation
export interface ConversationMessage {
  role: 'system' | 'user' | 'assistant';
  content: string;
  timestamp: string;
  addedNodeIds?: string[];  // Kort som drogs in vid detta meddelande
}

// Samtalsminne - en hel konversation
export interface Conversation {
  id: string;
  title: string;                    // AI-genererad eller manuell
  createdAt: string;
  updatedAt: string;
  messages: ConversationMessage[];
  contextNodeIds: string[];         // Vilka kort var involverade?
  provider: AIProvider;
  summary?: string;                 // AI-genererad sammanfattning
  themes?: string[];                // Upptäckta teman
  isArchived?: boolean;
}

// ============================================
// TRAIL/WANDERING SYSTEM
// ============================================

// Ett steg i en stig
export interface TrailWaypoint {
  nodeId: string;
  arrivedAt: string;              // ISO timestamp
  similarity?: number;            // Semantisk likhet till föregående waypoint
  semanticTheme?: string;         // AI-detekterat tema för kopplingen
}

// En stig genom semantiskt utrymme
export interface Trail {
  id: string;
  name: string;
  waypoints: TrailWaypoint[];
  parentTrailId?: string;         // För förgreningar - pekar på ursprungsstigen
  branchPointIndex?: number;      // Index i förälder där grenen startade
  createdAt: string;
  updatedAt: string;
  isActive: boolean;              // Utforskas just nu
  autoGenerated?: boolean;        // AI-föreslagen vs manuellt skapad
}

// Info om ett graviterat kort (vid vandring)
export interface GravitatingNode {
  nodeId: string;
  similarity: number;             // 0-1 semantisk likhet
  semanticTheme?: string;         // t.ex. "existentiellt", "praktiskt"
  themeColor?: string;            // Temafärg för highlighting
}

// Färgläge för gravitating nodes
export type GravitatingColorMode = 'similarity' | 'semantic';

// Vandringslägets tillstånd
export interface WanderingState {
  isActive: boolean;
  currentNodeId: string | null;
  gravitatingNodes: GravitatingNode[];
  minSimilarityThreshold: number; // Filter för graviterade kort
  showOnlyDifferentWords: boolean; // "Surface difference" mode
  colorMode: GravitatingColorMode; // 'similarity' = grön-cyan gradient, 'semantic' = temafärger
}

// Centralitet för hub-visualisering
export interface NodeCentrality {
  nodeId: string;
  connectionCount: number;
  normalizedCentrality: number;   // 0-1 skala
}
